### DISCUSSION TITLE
How to use triggers on schema based sharding?

### DISCUSSION THREAD

**Discussion by YoussefEgla** [citusdata/citus#7616] [Q&A]
I'm following this [example](https://docs.citusdata.com/en/v12.1/extra/triggers.html?highlight=trigger#triggers-on-distributed-tables) and using `run_command_on_colocated_placements` function.

```sql
SET search_path TO myapp;

CREATE TABLE IF NOT EXISTS little_vals (key int, val int);
CREATE TABLE IF NOT EXISTS big_vals    (key int, val int);

CREATE OR REPLACE FUNCTION embiggen() RETURNS TRIGGER AS $$
  BEGIN
    IF (TG_OP = 'INSERT') THEN
      EXECUTE format(
        'INSERT INTO %s (key, val) SELECT ($1).key, ($1).val*2;',
        TG_ARGV[0]
      ) USING NEW;
    END IF;
    RETURN NULL;
  END;
$$ LANGUAGE plpgsql;
```
```sql
SELECT citus_schema_distribute(myapp);
```
```sql
SELECT run_command_on_colocated_placements(
  'little_vals',
  'big_vals',
  $cmd$
    CREATE TRIGGER after_insert AFTER INSERT ON %s
      FOR EACH ROW EXECUTE PROCEDURE embiggen(%L)
  $cmd$
);
```

Then I run this query
```sql
INSERT INTO little_vals (key, val) VALUES (1, 2);
SELECT * FROM big_vals;
```
- `big_vals` is empty
- `little_vals` row added as expected.

Also I tried exactly as the example from the docs and got the same result.

I'm running on docker compose
```yaml
services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_pg_master"
    image: "citusdata/citus:12.1.3"
    ports: ["${COORDINATOR_EXTERNAL_PORT:-5432}:5432"]
    volumes:
      - pg_master:/var/lib/postgresql/data
    labels: [com.citusdata.role=Master]
    environment: &PG_ENV
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      PGUSER: "${POSTGRES_USER:-postgres}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_pg_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
      - pg_manager:/var/lib/postgresql/data
    depends_on: [master]
    environment: *PG_ENV
  pg_worker_0:
    image: "citusdata/citus:12.1.3"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
      - pg_worker_0:/var/lib/postgresql/data
    environment: *PG_ENV
  pg_worker_1:
    image: "citusdata/citus:12.1.3"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck
      - pg_worker_1:/var/lib/postgresql/data
    environment: *PG_ENV

```
