### ISSUE TITLE
master_append_table_to_shard() does not work using docker

### ISSUE THREAD

**Issue by tomcashman** [citusdata/citus#1964]
I'm currently using the official citus:7.2.0 docker compose file during an integration test and I receive the following error when using master_append_table_to_shard()

```sql
SELECT master_append_table_to_shard(102168, 'staging_table', 'localhost', 5435);
ERROR: could not make changes to shard 102168 on any node
```

where the shard ID was returned from the following function based on the append distribution documentation.

```sql
CREATE OR REPLACE FUNCTION select_shard(_distributedTable VARCHAR) RETURNS bigint AS $$
DECLARE
  shard_id bigint;
BEGIN
  SELECT shardid INTO shard_id
  FROM pg_dist_shard JOIN pg_dist_placement USING (shardid)
  WHERE logicalrelid = _distributedTable::regclass AND shardlength < 1024*1024*1024;

  IF shard_id IS NULL THEN
    /* no shard smaller than 1GB, create a new one */
    SELECT master_create_empty_shard(_distributedTable) INTO shard_id;
  END IF;

  RETURN shard_id;
END;
$$ LANGUAGE plpgsql;
```

I've tested on both citus:7.1.2 and citus:7.2.0 images with same result.

However, everything works as expected when using a baremetal deployment.

**Comment by sumedhpathak** [comment]
Did you also get this WARNING along with the above error:

`WARNING:  could not copy table "github_events_local" from "localhost:5432"`?

I think with Docker, you need to provide the internal host name `citus_master`, which it is able to translate to the master. Using `localhost` did not work for me either.

If i use `citus_master`, the append functions is able to connect and works fine.

**Comment by tomcashman** [comment]
Even with citus-master I get the same error. I had changed the docker compose yml to use a different port, don't know if this makes a difference?

```
worker_1   | 2018-01-24 14:48:33.672 UTC [216] STATEMENT:  SELECT worker_append_table_to_shard ('public.events_102016', 'stage_1', 'citus-master', 5435)
citus-master | 2018-01-24 14:48:33.673 UTC [110] WARNING:  could not copy table "stage_1" from "citus-master:5435"
citus-master | 2018-01-24 14:48:33.673 UTC [110] CONTEXT:  while executing command on citus_worker_1:5432
citus-master | 2018-01-24 14:48:33.674 UTC [110] ERROR:  could not make changes to shard 102016 on any node
```

```yml
version: '2.1'

services:
  master:
    container_name: "citus-master"
    image: 'citusdata/citus:7.2.0'
    ports: ["${MASTER_EXTERNAL_PORT:-5435}:5432"]
    labels: ['com.citusdata.role=Master']
  worker:
    image: 'citusdata/citus:7.2.0'
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
  manager:
    container_name: "citus-manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }                         
```
