### ISSUE TITLE
Master node reject all incoming connections

### ISSUE THREAD

**Issue by snaffi** [citusdata/citus#2402]
I've found very strange behaviour with Citus in Docker.

I've run my application and everything goes well, but after few hours my application was crashed because it can't connect to citus.

Docker version
`Docker version 18.06.1-ce, build e68fc7a`

```
citus_master   |  -<signal>, -s, --signal <signal>
citus_master   |                         specify the <signal> to be sent
citus_master   |  -l, --list=[<signal>]  list all signal names, or convert one to a name
citus_master   |  -L, --table            list all signal names in a nice table
citus_master   |
citus_master   |  -h, --help     display this help and exit
citus_master   |  -V, --version  output version information and exit
citus_master   |
citus_master   | For more details see kill(1).
citus_master   | 2018-09-19 10:34:05.406 UTC [16257] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   |
citus_master   | Usage:
citus_master   |  kill [options] <pid> [...]
citus_master   |
citus_master   | Options:
citus_master   |  <pid> [...]            send signal to every <pid> listed
citus_master   |  -<signal>, -s, --signal <signal>
citus_master   |                         specify the <signal> to be sent
citus_master   |  -l, --list=[<signal>]  list all signal names, or convert one to a name
citus_master   |  -L, --table            list all signal names in a nice table
citus_master   |
citus_master   |  -h, --help     display this help and exit
citus_master   |  -V, --version  output version information and exit
citus_master   |
citus_master   | For more details see kill(1).
citus_master   | 2018-09-19 10:36:21.675 UTC [370] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:25.951 UTC [382] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:30.176 UTC [394] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:34.431 UTC [405] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:38.684 UTC [415] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:42.951 UTC [426] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:47.227 UTC [439] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:51.543 UTC [450] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:36:55.818 UTC [461] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:00.024 UTC [474] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:04.233 UTC [485] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:08.421 UTC [495] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:12.606 UTC [506] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:16.811 UTC [517] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:21.013 UTC [527] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:25.204 UTC [538] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:29.376 UTC [549] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:33.564 UTC [563] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:37.809 UTC [573] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:42.001 UTC [584] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
citus_master   | 2018-09-19 10:37:46.190 UTC [596] FATAL:  pg_hba.conf rejects connection for host "172.19.0.2", user "postgres", database "my_database", SSL off
```

logs from manager

```
connected to master
found compose project: my_database
listening for events...
adding my_database_worker_1
removing my_database_worker_1
shutting down...
Traceback (most recent call last):
  File "./manager.py", line 97, in <module>
    main()
  File "./manager.py", line 93, in main
    docker_checker()
  File "./manager.py", line 60, in docker_checker
    conn = connect_to_master()
  File "./manager.py", line 47, in connect_to_master
    (postgres_db, postgres_user, citus_host, postgres_pass))
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  pg_hba.conf rejects connection for host "172.19.0.3", user "postgres", database "my_database", SSL off
```

I'm using default pg_hba.conf which allow all incoming connection

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

host all all all trust
```

docker-compose.yml

```
version: '2.1'
services:
  master:
    container_name: "citus_master"
    image: 'citusdata/citus:7.5.1'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master']
    environment:
     - "POSTGRES_DB=my_database"
    volumes:
     - /var/lib/citus_master:/var/lib/postgresql/data
  worker:
    image: 'citusdata/citus:7.5.1'
    labels: ['com.citusdata.role=Worker']
    environment:
     - "POSTGRES_DB=my_database"
    volumes:
     - /var/lib/citus_worker_1:/var/lib/postgresql/data
    depends_on: { manager: { condition: service_healthy } }
  manager:
    container_name: "citus_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    environment:
     - "POSTGRES_DB=my_database"
    depends_on: { master: { condition: service_healthy } }
```

Restart didn't help.

Drop all data volumes help me.
