### ISSUE TITLE
Random error function assign_distributed_transaction_id(integer, integer, unknown) does not exist

### ISSUE THREAD

**Issue by bologer** [citusdata/citus#3800]
I'm running lastest Docker version of Citus. 

Info: 

```
dev=# \dx
                 List of installed extensions
  Name   | Version |   Schema   |         Description          
---------+---------+------------+------------------------------
 citus   | 8.3-1   | pg_catalog | Citus distributed database
```

Docker compose: 

```yaml
version: '2.1'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:8.3.2'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    labels: ['com.citusdata.role=Master']
  worker:
    image: 'citusdata/citus:8.3.2'
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
```

Created new database following instructions [here](http://docs.citusdata.com/en/v9.2/admin_guide/cluster_management.html#creating-a-new-database), however when I try to run transactional SLQ queries it shows me the following error: 
  
```bash
ERROR:  function assign_distributed_transaction_id(integer, integer, unknown) does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
CONTEXT:  while executing command on citus_worker_1:5432
```

I assume it is failing on this `create_distributed_table` because it fails right after `CREATE TABLE ...` SQL.

I have follows steps mentioned in the link carefully, all extensions are created.

The only part I'm confused about is this: 

> In the new db on every worker, manually run:
> `CREATE EXTENSION citus;`

If it means I need to connect to a worker container and create extension, then sure, it is done as well. 

Thanks for help in advance!
